name: "Branchlog2"
description: "Creates a changelog between two branches"
author: "Aléxia Balionis"
branding:
  icon: "git-merge"
  color: "purple"
inputs:
  token: # id of input
    description: "Access token"
    required: true
  repository:
    description: "Name of the repo to search into"
    required: true
  owner:
    description: "Name of the organization the repo belongs to"
    default: "olxbr"
    required: true
  base_branch:
    description: "Branch which the PR is going into. ie: main"
    default: "main"
    required: true
  base_branch_pr_title:
    description: "Action will get all PRs merged after this one"
    default: "Promote homolog to production"
    required: true
  feature_branch:
    description: "Branch that contains feature requests to be merged. ie: homolog"
    default: "homolog"
    required: true
  pr_state:
    description: "Search for PRs in which state: open, closed, merged"
    default: "closed"
    required: true
outputs:
  message: # output will be available to future steps
    description: "List of received PRs"
runs:
  using: "node16"
  main: "dist/index.js"
